version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"

  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000" # Kong Proxy
      - "8443:8443" # Kong Proxy SSL
      - "8001:8001" # Kong Admin API
      - "8444:8444" # Kong Admin API SSL
    depends_on:
      - kong-database
  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337" # Konga UI
    depends_on:
      - kong